import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:pseudolearn_app/application/export/export_state.dart';
import 'package:pseudolearn_app/domain/model/export/target_language_id.dart';
import 'package:pseudolearn_app/presentation/export/export_tab_view.dart';
import 'package:pseudolearn_app/presentation/l10n/generated/app_localizations.dart';
import 'package:pseudolearn_app/presentation/shell/design_canvas.dart';
import 'package:pseudolearn_app/presentation/theme/app_theme.dart';

Future<void> _pumpExportTab(
  WidgetTester tester, {
  required Size size,
  required ThemeData theme,
  required ExportState state,
}) async {
  tester.view.physicalSize = size;
  tester.view.devicePixelRatio = 1.0;
  addTearDown(tester.view.resetPhysicalSize);
  addTearDown(tester.view.resetDevicePixelRatio);

  await tester.pumpWidget(
    MaterialApp(
      theme: theme,
      locale: const Locale('es'),
      localizationsDelegates: const [
        AppLocalizations.delegate,
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
      ],
      supportedLocales: AppLocalizations.supportedLocales,
      home: Scaffold(
        body: DesignCanvas(
          child: ExportTabView(
            state: state,
            onLanguageSelected: (_) {},
          ),
        ),
      ),
    ),
  );
  await tester.pumpAndSettle();
}

void main() {
  const exportReadyState = ExportState(
    selectedLanguage: TargetLanguageId.python,
    status: ExportStatus.ready,
    exportedCode: '''# Generated by PseudoLearn - Target: Python

def main():
    x = 42
    print(x)

if __name__ == "__main__":
    main()''',
  );

  group('ExportTabView Goldens (PANT-02D-F2) — three widths, two themes', () {
    testWidgets('compact · light', (tester) async {
      await _pumpExportTab(
        tester,
        size: const Size(360, 640),
        theme: AppTheme.light(),
        state: exportReadyState,
      );
      await expectLater(
        find.byType(ExportTabView),
        matchesGoldenFile('goldens/export_tab_compact_light.png'),
      );
    });

    testWidgets('compact · dark', (tester) async {
      await _pumpExportTab(
        tester,
        size: const Size(360, 640),
        theme: AppTheme.dark(),
        state: exportReadyState,
      );
      await expectLater(
        find.byType(ExportTabView),
        matchesGoldenFile('goldens/export_tab_compact_dark.png'),
      );
    });

    testWidgets('medium · light', (tester) async {
      await _pumpExportTab(
        tester,
        size: const Size(600, 800),
        theme: AppTheme.light(),
        state: exportReadyState,
      );
      await expectLater(
        find.byType(ExportTabView),
        matchesGoldenFile('goldens/export_tab_medium_light.png'),
      );
    });

    testWidgets('medium · dark', (tester) async {
      await _pumpExportTab(
        tester,
        size: const Size(600, 800),
        theme: AppTheme.dark(),
        state: exportReadyState,
      );
      await expectLater(
        find.byType(ExportTabView),
        matchesGoldenFile('goldens/export_tab_medium_dark.png'),
      );
    });

    testWidgets('expanded · light', (tester) async {
      await _pumpExportTab(
        tester,
        size: const Size(960, 800),
        theme: AppTheme.light(),
        state: exportReadyState,
      );
      await expectLater(
        find.byType(ExportTabView),
        matchesGoldenFile('goldens/export_tab_expanded_light.png'),
      );
    });

    testWidgets('expanded · dark', (tester) async {
      await _pumpExportTab(
        tester,
        size: const Size(960, 800),
        theme: AppTheme.dark(),
        state: exportReadyState,
      );
      await expectLater(
        find.byType(ExportTabView),
        matchesGoldenFile('goldens/export_tab_expanded_dark.png'),
      );
    });
  });
}
