import 'package:flutter_test/flutter_test.dart';
import 'package:pseudolearn_app/domain/model/export/export_result.dart';
import 'package:pseudolearn_app/domain/model/export/target_language_id.dart';
import 'package:pseudolearn_app/domain/model/profiles/syntax_profile_id.dart';
import 'package:pseudolearn_app/engine/export/core_program_exporter.dart';

void main() {
  final exporter = CoreProgramExporter();

  group('CoreProgramExporter Engine Tests', () {
    test('exports clean algorithm to Python', () {
      const source = '''
Algoritmo Test
  Definir x Como Entero
  x <- 42
  Escribir x
FinAlgoritmo
''';
      final result = exporter.export(
        sourceCode: source,
        targetLanguage: TargetLanguageId.python,
        profileId: SyntaxProfileId.classicSpanish,
      );

      expect(result, isA<ExportSuccess>());
      final success = result as ExportSuccess;
      expect(success.program.targetLanguage, equals(TargetLanguageId.python));
      expect(success.program.sourceCode, startsWith('# Generated by PseudoLearn'));
      expect(success.program.sourceCode, contains('def main():'));
      expect(success.program.sourceCode, contains('x = 42'));
      expect(success.program.sourceCode, contains('print(x)'));
    });

    test('exports clean algorithm to Rust', () {
      const source = '''
Algoritmo Test
  Definir x Como Entero
  x <- 42
  Escribir x
FinAlgoritmo
''';
      final result = exporter.export(
        sourceCode: source,
        targetLanguage: TargetLanguageId.rust,
        profileId: SyntaxProfileId.classicSpanish,
      );

      expect(result, isA<ExportSuccess>());
      final success = result as ExportSuccess;
      expect(success.program.targetLanguage, equals(TargetLanguageId.rust));
      expect(success.program.sourceCode, startsWith('// Generated by PseudoLearn'));
      expect(success.program.sourceCode, contains('fn main() {'));
      expect(success.program.sourceCode, contains('x = 42;'));
      expect(success.program.sourceCode, contains('println!'));
    });

    test('returns ExportAnalysisError when source code has syntax errors', () {
      const invalidSource = 'Algoritmo Incompleto x <-';
      final result = exporter.export(
        sourceCode: invalidSource,
        targetLanguage: TargetLanguageId.python,
        profileId: SyntaxProfileId.classicSpanish,
      );

      expect(result, isA<ExportAnalysisError>());
    });

    test('returns ExportAnalysisError when source code has semantic errors', () {
      const semanticErrorSource = '''
Algoritmo SemanticError
  Definir x Como Entero
  x <- "texto invalido"
FinAlgoritmo
''';
      final result = exporter.export(
        sourceCode: semanticErrorSource,
        targetLanguage: TargetLanguageId.python,
        profileId: SyntaxProfileId.classicSpanish,
      );

      expect(result, isA<ExportAnalysisError>());
    });

    test('exports factorial algorithm with For loop to Python and Rust cleanly', () {
      const source = '''
Algoritmo Factorial
  Definir n Como Entero
  Definir f Como Entero
  Definir i Como Entero
  n <- 5
  f <- 1
  Para i <- 1 Hasta n Con Paso 1 Hacer
    f <- f * i
  FinPara
  Escribir "Factorial: ", f
FinAlgoritmo
''';
      final pyResult = exporter.export(
        sourceCode: source,
        targetLanguage: TargetLanguageId.python,
        profileId: SyntaxProfileId.classicSpanish,
      );
      expect(pyResult, isA<ExportSuccess>());
      final pySuccess = pyResult as ExportSuccess;
      expect(pySuccess.program.sourceCode, contains('for i in range(1, n + 1, 1):'));
      expect(pySuccess.program.sourceCode, contains('f = f * i'));
      expect(pySuccess.program.sourceCode, isNot(contains('# Unsupported statement')));

      final rsResult = exporter.export(
        sourceCode: source,
        targetLanguage: TargetLanguageId.rust,
        profileId: SyntaxProfileId.classicSpanish,
      );
      expect(rsResult, isA<ExportSuccess>());
      final rsSuccess = rsResult as ExportSuccess;
      expect(rsSuccess.program.sourceCode, contains('for i in (1..=n).step_by((1) as usize) {'));
      expect(rsSuccess.program.sourceCode, contains('f = f * i;'));
      expect(rsSuccess.program.sourceCode, isNot(contains('// unsupported statement')));
    });

    test('exports RepeatUntil loop to Python and Rust cleanly', () {
      const source = '''
Algoritmo RepetirTest
  Definir c Como Entero
  c <- 0
  Repetir
    c <- c + 1
  Hasta Que c >= 5
  Escribir c
FinAlgoritmo
''';
      final pyResult = exporter.export(
        sourceCode: source,
        targetLanguage: TargetLanguageId.python,
        profileId: SyntaxProfileId.classicSpanish,
      );
      expect(pyResult, isA<ExportSuccess>());
      final pySuccess = pyResult as ExportSuccess;
      expect(pySuccess.program.sourceCode, contains('while True:'));
      expect(pySuccess.program.sourceCode, contains('if c >= 5:'));
      expect(pySuccess.program.sourceCode, contains('break'));

      final rsResult = exporter.export(
        sourceCode: source,
        targetLanguage: TargetLanguageId.rust,
        profileId: SyntaxProfileId.classicSpanish,
      );
      expect(rsResult, isA<ExportSuccess>());
      final rsSuccess = rsResult as ExportSuccess;
      expect(rsSuccess.program.sourceCode, contains('loop {'));
      expect(rsSuccess.program.sourceCode, contains('if c >= 5 {'));
      expect(rsSuccess.program.sourceCode, contains('break;'));
    });

    test('exports Switch Segun to Python match and Rust match', () {
      const source = '''
Algoritmo SegunTest
  Definir op Como Entero
  op <- 2
  Segun op Hacer
    1:
      Escribir "Uno"
    2:
      Escribir "Dos"
    De Otro Modo:
      Escribir "Otro"
  FinSegun
FinAlgoritmo
''';
      final pyResult = exporter.export(
        sourceCode: source,
        targetLanguage: TargetLanguageId.python,
        profileId: SyntaxProfileId.classicSpanish,
      );
      expect(pyResult, isA<ExportSuccess>());
      final pySuccess = pyResult as ExportSuccess;
      expect(pySuccess.program.sourceCode, contains('match op:'));
      expect(pySuccess.program.sourceCode, contains('case 1:'));
      expect(pySuccess.program.sourceCode, contains('case _:'));

      final rsResult = exporter.export(
        sourceCode: source,
        targetLanguage: TargetLanguageId.rust,
        profileId: SyntaxProfileId.classicSpanish,
      );
      expect(rsResult, isA<ExportSuccess>());
      final rsSuccess = rsResult as ExportSuccess;
      expect(rsSuccess.program.sourceCode, contains('match op {'));
      expect(rsSuccess.program.sourceCode, contains('1 => {'));
      expect(rsSuccess.program.sourceCode, contains('_ => {'));
    });

    test('exports Dimension arrays to Python and Rust', () {
      const source = '''
Algoritmo ArrayTest
  Dimension a[10] Como Entero
  a[0] <- 42
  Escribir a[0]
FinAlgoritmo
''';
      final pyResult = exporter.export(
        sourceCode: source,
        targetLanguage: TargetLanguageId.python,
        profileId: SyntaxProfileId.classicSpanish,
      );
      expect(pyResult, isA<ExportSuccess>());
      final pySuccess = pyResult as ExportSuccess;
      expect(pySuccess.program.sourceCode, contains('a = [0] * (10)'));
      expect(pySuccess.program.sourceCode, contains('a[0] = 42'));

      final rsResult = exporter.export(
        sourceCode: source,
        targetLanguage: TargetLanguageId.rust,
        profileId: SyntaxProfileId.classicSpanish,
      );
      expect(rsResult, isA<ExportSuccess>());
      final rsSuccess = rsResult as ExportSuccess;
      expect(rsSuccess.program.sourceCode, contains('let mut a = vec![0; (10) as usize];'));
      expect(rsSuccess.program.sourceCode, contains('a[(0) as usize] = 42;'));
    });
  });
}
