import 'package:flutter_test/flutter_test.dart';
import 'package:pseudolearn_app/domain/model/export/target_language_id.dart';
import 'package:pseudolearn_app/engine/export/target_code_header.dart';

void main() {
  group('Exported code header', () {
    test('signs Python with its own line comment marker', () {
      expect(targetCodeHeader(TargetLanguageId.python), '# Generated by PseudoLearn - Target: Python');
    });

    test('signs Rust with its own line comment marker', () {
      expect(targetCodeHeader(TargetLanguageId.rust), '// Generated by PseudoLearn - Target: Rust');
    });

    test('every target is signed, and all signatures say the same thing', () {
      for (final target in TargetLanguageId.values) {
        final header = targetCodeHeader(target);
        expect(header, contains('Generated by PseudoLearn'));
        expect(header, endsWith(target.displayName));
      }
    });

    test('the header is a single line, so it cannot break the code it precedes', () {
      for (final target in TargetLanguageId.values) {
        expect(targetCodeHeader(target).contains('\n'), isFalse);
      }
    });
  });
}
