part of 'english_profile.dart';

const Map<DiagnosticCode, Severity> _classASeverity = {
  DiagnosticCode.unrecognizedCharacter: Severity.error,
  DiagnosticCode.unterminatedString: Severity.error,
  DiagnosticCode.invalidEscapeSequence: Severity.error,
  DiagnosticCode.expectedExpression: Severity.error,
  DiagnosticCode.unexpectedTokenInExpression: Severity.error,
  DiagnosticCode.unclosedParenthesis: Severity.error,
  DiagnosticCode.unexpectedClosingParenthesis: Severity.error,
  DiagnosticCode.emptyParentheses: Severity.error,
  DiagnosticCode.unclosedBracket: Severity.error,
  DiagnosticCode.emptyIndexList: Severity.error,
  DiagnosticCode.trailingComma: Severity.error,
  DiagnosticCode.chainedArrayAccess: Severity.error,
  DiagnosticCode.expectedAlgorithmStart: Severity.error,
  DiagnosticCode.expectedAlgorithmName: Severity.error,
  DiagnosticCode.unclosedAlgorithm: Severity.error,
  DiagnosticCode.unexpectedTokenOutsideAlgorithm: Severity.error,
  DiagnosticCode.missingStatementTerminator: Severity.error,
  DiagnosticCode.expectedIdentifierInDeclaration: Severity.error,
  DiagnosticCode.reservedLexemeUsedAsName: Severity.error,
  DiagnosticCode.expectedTypeConnector: Severity.error,
  DiagnosticCode.expectedType: Severity.error,
  DiagnosticCode.initializationInDeclarationNotAllowed: Severity.error,
  DiagnosticCode.expectedIdentifierInDimension: Severity.error,
  DiagnosticCode.emptyDimensionList: Severity.error,
  DiagnosticCode.invalidAssignmentTarget: Severity.error,
  DiagnosticCode.expectedAssignmentOperator: Severity.error,
  DiagnosticCode.expectedReadTarget: Severity.error,
  DiagnosticCode.invalidReadTarget: Severity.error,
  DiagnosticCode.unexpectedModifierPosition: Severity.error,
  DiagnosticCode.duplicateModifier: Severity.error,
  DiagnosticCode.expectedThenKeyword: Severity.error,
  DiagnosticCode.unclosedIfStatement: Severity.error,
  DiagnosticCode.duplicateElseClause: Severity.error,
  DiagnosticCode.expectedDoKeyword: Severity.error,
  DiagnosticCode.expectedBranchSeparator: Severity.error,
  DiagnosticCode.nonLiteralSwitchCaseLabel: Severity.error,
  DiagnosticCode.duplicateSwitchCaseLabel: Severity.error,
  DiagnosticCode.duplicateDefaultCase: Severity.error,
  DiagnosticCode.invalidDefaultCasePosition: Severity.error,
  DiagnosticCode.unclosedSwitchStatement: Severity.error,
  DiagnosticCode.unclosedWhileStatement: Severity.error,
  DiagnosticCode.unclosedRepeatStatement: Severity.error,
  DiagnosticCode.expectedForLoopVariable: Severity.error,
  DiagnosticCode.expectedToKeyword: Severity.error,
  DiagnosticCode.missingStepClause: Severity.error,
  DiagnosticCode.unclosedForStatement: Severity.error,
  DiagnosticCode.mismatchedBlockEnd: Severity.error,
  DiagnosticCode.unexpectedBlockEnd: Severity.error,
  DiagnosticCode.unexpectedStatement: Severity.error,
  DiagnosticCode.unsupportedStructuredConstruct: Severity.error,
  DiagnosticCode.expectedSubroutineName: Severity.error,
  DiagnosticCode.expectedSubroutineLeftParenthesis: Severity.error,
  DiagnosticCode.unclosedSubroutine: Severity.error,
  DiagnosticCode.subroutineInsideAlgorithm: Severity.error,
  DiagnosticCode.subroutineInsideSubroutine: Severity.error,
  DiagnosticCode.returnOutsideSubroutine: Severity.error,
  DiagnosticCode.expectedParameterName: Severity.error,
  DiagnosticCode.duplicatePassingModifier: Severity.error,
  DiagnosticCode.passingModifierBeforeParameterName: Severity.error,
  DiagnosticCode.invalidArrayReturnType: Severity.error,
  DiagnosticCode.multipleAlgorithms: Severity.error,
  DiagnosticCode.unexpectedTokenOutsideProgramUnit: Severity.error,
  DiagnosticCode.expectedClassName: Severity.error,
  DiagnosticCode.unclosedClass: Severity.error,
  DiagnosticCode.classInsideAlgorithm: Severity.error,
  DiagnosticCode.classInsideSubroutine: Severity.error,
  DiagnosticCode.nestedClassNotSupported: Severity.error,
  DiagnosticCode.subroutineInsideClass: Severity.error,
  DiagnosticCode.multipleInheritanceNotSupported: Severity.error,
  DiagnosticCode.duplicateVisibilityModifier: Severity.error,
  DiagnosticCode.constructorVisibilityNotAllowed: Severity.error,
  DiagnosticCode.constructorReturnTypeNotAllowed: Severity.error,
  DiagnosticCode.duplicateConstructor: Severity.error,
  DiagnosticCode.methodNamedAsClass: Severity.error,
  DiagnosticCode.methodOutsideClass: Severity.error,
  DiagnosticCode.constructorOutsideClass: Severity.error,
  DiagnosticCode.unclosedMethod: Severity.error,
  DiagnosticCode.expectedClassNameInInstantiation: Severity.error,
  DiagnosticCode.missingInstantiationParentheses: Severity.error,
  DiagnosticCode.expectedMemberNameAfterDot: Severity.error,
  DiagnosticCode.thisOutsideMethod: Severity.error,
  DiagnosticCode.expectedMemberNameAfterThis: Severity.error,
  DiagnosticCode.superOutsideMethod: Severity.error,
  DiagnosticCode.superInClassWithoutSuperclass: Severity.error,
  DiagnosticCode.superNotFollowedByCall: Severity.error,
  DiagnosticCode.unsupportedInterfaceConstruct: Severity.error,
  DiagnosticCode.unsupportedAbstractConstruct: Severity.error,
  DiagnosticCode.unsupportedStaticConstruct: Severity.error,
  DiagnosticCode.unsupportedProtectedConstruct: Severity.error,
  DiagnosticCode.unsupportedGenericsConstruct: Severity.error,
  DiagnosticCode.unsupportedExceptionConstruct: Severity.error,
  DiagnosticCode.maxDiagnosticsExceeded: Severity.error,
  DiagnosticCode.variableUsedBeforeDeclaration: Severity.error,
  DiagnosticCode.duplicateVariableDeclaration: Severity.error,
  DiagnosticCode.duplicateParameterName: Severity.error,
  DiagnosticCode.duplicateSubroutine: Severity.error,
  DiagnosticCode.duplicateClass: Severity.error,
  DiagnosticCode.classAndSubroutineSameName: Severity.error,
  DiagnosticCode.subroutineAndVariableSameName: Severity.error,
  DiagnosticCode.undeclaredSubroutine: Severity.error,
  DiagnosticCode.undeclaredClass: Severity.error,
  DiagnosticCode.undeclaredSuperclass: Severity.error,
  DiagnosticCode.circularInheritance: Severity.error,
  DiagnosticCode.duplicateMember: Severity.error,
  DiagnosticCode.inheritedAttributeShadowed: Severity.error,
  DiagnosticCode.incompatibleMethodOverride: Severity.error,
  DiagnosticCode.missingSuperConstructorCall: Severity.error,
  DiagnosticCode.invalidSuperConstructorCallPosition: Severity.error,
  DiagnosticCode.returnWithValueInConstructor: Severity.error,
  DiagnosticCode.identifierMatchesFieldWithoutThis: Severity.error,
  DiagnosticCode.undefinedMember: Severity.error,
  DiagnosticCode.incompatibleTypesInAssignment: Severity.error,
  DiagnosticCode.incompatibleOperandTypes: Severity.error,
  DiagnosticCode.cannotConcatenateNumberWithText: Severity.error,
  DiagnosticCode.divOrModWithRealOperand: Severity.error,
  DiagnosticCode.noOrderBetweenBooleans: Severity.error,
  DiagnosticCode.argumentCountMismatch: Severity.error,
  DiagnosticCode.incompatibleArgumentType: Severity.error,
  DiagnosticCode.byReferenceArgumentRequiresDesignator: Severity.error,
  DiagnosticCode.byReferenceArgumentTypeMismatch: Severity.error,
  DiagnosticCode.incompatibleReturnType: Severity.error,
  DiagnosticCode.returnExpressionInVoidSubroutine: Severity.error,
  DiagnosticCode.missingReturnExpression: Severity.error,
  DiagnosticCode.subroutineWithoutReturn: Severity.error,
  DiagnosticCode.callAsExpressionWithoutReturnType: Severity.error,
  DiagnosticCode.nonBooleanCondition: Severity.error,
  DiagnosticCode.nonIntegerForBound: Severity.error,
  DiagnosticCode.nonIntegerArrayIndex: Severity.error,
  DiagnosticCode.arrayDimensionCountMismatch: Severity.error,
  DiagnosticCode.arrayCannotBeUsedAsValue: Severity.error,
  DiagnosticCode.objectCannotBeWritten: Severity.error,
  DiagnosticCode.typeConflictOnInferredVariable: Severity.error,
  DiagnosticCode.integerLiteralOutOfRange: Severity.error,
  DiagnosticCode.divisionByZero: Severity.error,
  DiagnosticCode.integerOverflow: Severity.error,
  DiagnosticCode.nonFiniteRealResult: Severity.error,
  DiagnosticCode.negativeIntegerExponent: Severity.error,
  DiagnosticCode.arrayIndexOutOfRange: Severity.error,
  DiagnosticCode.negativeArraySize: Severity.error,
  DiagnosticCode.zeroStepInCountedLoop: Severity.error,
  DiagnosticCode.recursionDepthExceeded: Severity.error,
  DiagnosticCode.uninitializedVariableRead: Severity.error,
  DiagnosticCode.stringToNumberConversionFailed: Severity.error,
  DiagnosticCode.stringPositionOutOfRange: Severity.error,
  DiagnosticCode.invalidCharacterCode: Severity.error,
  DiagnosticCode.subroutineEndedWithoutReturn: Severity.error,
  DiagnosticCode.privateMemberAccess: Severity.error,
};

const Map<DiagnosticCode, Severity> _classBSeverityStrict = {
  DiagnosticCode.undeclaredVariable: Severity.error,
  DiagnosticCode.variableUsedUninitialized: Severity.error,
  DiagnosticCode.incompatibleSwitchCaseType: Severity.error,
};

const Map<DiagnosticCode, Severity> _classBSeverityFlexible = {
  DiagnosticCode.undeclaredVariable: Severity.warning,
  DiagnosticCode.variableUsedUninitialized: Severity.warning,
  DiagnosticCode.incompatibleSwitchCaseType: Severity.warning,
};

const Map<DiagnosticCode, Severity> _classCSeverity = {
  DiagnosticCode.variableDeclaredNeverUsed: Severity.warning,
  DiagnosticCode.variableAssignedNeverRead: Severity.warning,
  DiagnosticCode.unusedParameter: Severity.warning,
  DiagnosticCode.unusedSubroutine: Severity.warning,
  DiagnosticCode.realEqualityComparison: Severity.warning,
  DiagnosticCode.discardedReturnValue: Severity.warning,
};

const Map<DiagnosticCode, Severity> _classDSeverity = {
  DiagnosticCode.inferredVariableType: Severity.info,
  DiagnosticCode.widenedVariableType: Severity.info,
};

const Map<DiagnosticCode, Severity> _classESeverity = {
  DiagnosticCode.readValueTypeMismatch: Severity.warning,
};

const Map<DiagnosticCode, Severity> _strictSeverityPolicy = {
  ..._classASeverity,
  ..._classBSeverityStrict,
  ..._classCSeverity,
  ..._classDSeverity,
  ..._classESeverity,
};

const Map<DiagnosticCode, Severity> _flexibleSeverityPolicy = {
  ..._classASeverity,
  ..._classBSeverityFlexible,
  ..._classCSeverity,
  ..._classDSeverity,
  ..._classESeverity,
};
