import '../../domain/model/export/target_language_id.dart';

const Map<TargetLanguageId, String> _lineCommentMarkers = <TargetLanguageId, String>{
  TargetLanguageId.python: '#',
  TargetLanguageId.rust: '//',
};

String targetCodeHeader(TargetLanguageId targetLanguage) =>
    '${_lineCommentMarkers[targetLanguage]!} Generated by PseudoLearn - Target: ${targetLanguage.displayName}';
